# Generated by Django 5.2 on 2025-04-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('groceries', 'Groceries'), ('rent', 'Rent'), ('salary', 'Salary'), ('tip', 'Tip'), ('food', 'Food'), ('medical', 'Medical'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('transportation', 'Transportation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
